name: Build and Release

on:
  push:
    branches:
      - main #

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
      fail-fast: false # 如果某个构建失败，不阻止其他构建继续

    if: contains(github.event.head_commit.message, 'build')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.23' # 根据你的 Go 版本修改

      - name: Get current timestamp
        id: timestamp
        run: echo "TIMESTAMP=$(date +'%Y%m%d%H%M%S')" >> "$GITHUB_OUTPUT"

      - name: Build
        run: |
          GOOS=${{ matrix.goos }}
          GOARCH=${{ matrix.goarch }}
          output_name="trufflehog-${{ matrix.goos }}-${{ matrix.goarch }}-${{ steps.timestamp.outputs.TIMESTAMP }}" # 替换为你的项目名称
          go build -ldflags "-w -s" -o "${output_name}" .
          echo "OUTPUT_FILE=${output_name}" >> "$GITHUB_ENV" # 将输出文件名设置为环境变量

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output-${{ steps.timestamp.outputs.TIMESTAMP }}
          path: ${{ env.OUTPUT_FILE }}

  create-release:
    needs: build-and-release # Depends on the build job
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.event.head_commit.message, 'build')

    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: build-output-${{ needs.build.outputs.timestamp }}
          path: release-assets

      - name: Set Release Tag
        run: echo "RELEASE_TAG=${{ needs.build.outputs.timestamp }}" >> "$GITHUB_ENV"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ env.RELEASE_TAG }}
          RELEASE_NAME: Release ${{ env.RELEASE_TAG }}
        with:
          files: release-assets/* # Upload all files in the release-assets directory