name: Build and Release

on:
  push:
    branches:
      - main # 或者你主要开发的分支名称

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
      fail-fast: false # 如果某个构建失败，不阻止其他构建继续

    if: contains(github.event.head_commit.message, 'build')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.23' # 根据你的 Go 版本修改

      - name: Get current timestamp
        id: timestamp
        run: echo "TIMESTAMP=$(date +'%Y%m%d%H%M%S')" >> "$GITHUB_OUTPUT"

      - name: Build
        run: |
          GOOS=${{ matrix.goos }}
          GOARCH=${{ matrix.goarch }}
          output_name="trufflehog-${{ matrix.goos }}-${{ matrix.goarch }}-${{ steps.timestamp.outputs.TIMESTAMP }}" # 替换为你的项目名称
          go build -o "${output_name}" .
          echo "OUTPUT_FILE=${output_name}" >> "$GITHUB_ENV" # 将输出文件名设置为环境变量

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output-${{ steps.timestamp.outputs.TIMESTAMP }}
          path: ${{ env.OUTPUT_FILE }}

  create-release:
    needs: build # 依赖于 build job 完成
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.event.head_commit.message, 'build')

    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: build-output-${{ needs.build.outputs.timestamp }}
          path: release-assets

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.build.outputs.timestamp }}
          name: Release ${{ needs.build.outputs.timestamp }}
          files: release-assets/* # 上传 release-assets 目录下的所有文件
          token: ${{ secrets.GITHUB_TOKEN }}