name: Go Build and Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    if: contains(github.event.head_commit.message, 'build')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.23

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist --skip-validate
          workdir: v2/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOPATH: "/home/runner/go"

      - name: Set up Go 1.23
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'

      - name: Zip files
        run: zip -r v2/dist/trufflehog_archive.zip v2/dist/trufflehog* tools/* README.md

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: v2/dist/trufflehog*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
          draft: true