name: Build and Release

on:
  push:
    branches:
      - main # 或者你主要开发的分支名称
    commits:
      - 'build*' # 匹配包含 "build" 开头的 commit 信息

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
      fail-fast: false # 如果某个构建失败，不阻止其他构建继续

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.18' # 根据你的 Go 版本修改

      - name: Get current timestamp
        id: timestamp
        run: echo "TIMESTAMP=$(date +'%Y%m%d%H%M%S')" >> "$GITHUB_OUTPUT"

      - name: Build
        run: |
          GOOS=${{ matrix.goos }}
          GOARCH=${{ matrix.goarch }}
          output_name="trufflehog-${{ matrix.goos }}-${{ matrix.goarch }}-${{ steps.timestamp.outputs.TIMESTAMP }}" # 替换为你的项目名称
          go build -o "${output_name}" .

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'push' && contains(github.event.head_commit.message, 'build')
        with:
          tag_name: ${{ steps.timestamp.outputs.TIMESTAMP }}
          name: Release ${{ steps.timestamp.outputs.TIMESTAMP }}
          files: |
            trufflehog-linux-amd64-${{ steps.timestamp.outputs.TIMESTAMP }}
            trufflehog-linux-arm64-${{ steps.timestamp.outputs.TIMESTAMP }}
            trufflehog-windows-amd64-${{ steps.timestamp.outputs.TIMESTAMP }}.exe
            trufflehog-windows-arm64-${{ steps.timestamp.outputs.TIMESTAMP }}.exe
            trufflehog-darwin-amd64-${{ steps.timestamp.outputs.TIMESTAMP }}
            trufflehog-darwin-arm64-${{ steps.timestamp.outputs.TIMESTAMP }}
          token: ${{ secrets.GITHUB_TOKEN }}